# -*- coding: utf-8 -*-
"""Data_Visualization_Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZdmsG1-6VYsvd7ajMXm0p_56S4i1X2B

#Task 1
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df1 = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/world-happiness-report-2021.csv")

df1.head()

df1.tail(10)

df1.info()
print("Observation: Attributes Country name and Regional indicator are object. All attributes, except Country name and Regional indicator, are float type.\n")

df1.describe()

print("Missing Values?\n")
df1.isnull().sum()

countries = df1.loc[(df1["Regional indicator"]=="Western Europe")]
print("\nNumber of Unique Western Eurpoe Countries:",len(countries["Country name"].unique()) )
print("\nUnique Western Eurpoe Countries:",countries["Country name"].unique())

df1.loc[(df1["Country name"]=="India")]

"""#Task 2"""

df1 = df1.sort_values(by="Generosity",ascending=False)
top_east_asian = (df1.loc[(df1["Regional indicator"]=="East Asia")]).head()
top_east_asian

#Build a plot (line plot) that shows the variation of 'Ladder score' among the above 5 east asian countries (based on generosity)
#df1 = df1.sort_values(by="Generosity",ascending=False)
#top_east_asian = (df1.loc[(df1["Regional indicator"]=="East Asia")]).head()

x = plt.plot(top_east_asian["Generosity"],top_east_asian["Ladder score"])
plt.title("Relationship of Ladder Score and Generosity among 5 East Asian Countries")
plt.xlabel("Generosity")
plt.ylabel("Ladder score")
plt.show()

#Build a plot that shows the variation of 'Ladder score' among the 5 south east asian countries
top_south_asian = (df1.loc[(df1["Regional indicator"]=="South Asia")]).head()

y = plt.plot(top_south_asian["Generosity"],top_south_asian["Ladder score"])
plt.title("Relationship of Ladder Score and Generosity among 5 South Asian Countries")
plt.xlabel("Generosity")
plt.ylabel("Ladder score")
plt.show()

#Create a dataframe object : df_2021 with the following countries: 'China', 'Nepal', 'Bangladesh', 'Pakistan', 'Myanmar', 'India', 'Afghanistan'. Now, build a scatter plot to show the relation these countries vs their 'Logged GDP per capita'

target_countries = ["China","Nepal","Bangladesh","Pakistan","Myanmar","India","Afghanistan"]
df_2021 = df1.loc[ (df1["Country name"]==target_countries[0]) | (df1["Country name"]==target_countries[1]) | (df1["Country name"]==target_countries[2])|(df1["Country name"]==target_countries[3]) |(df1["Country name"]==target_countries[4]) |(df1["Country name"]==target_countries[5]) | (df1["Country name"]==target_countries[6]) ]

plt.scatter(df_2021["Country name"],df_2021["Logged GDP per capita"])
plt.title("Logged GDP Per Capita of 7 Countries")
plt.xlabel("Countries")
plt.ylabel("Logged GDP per capita")
plt.show()