# -*- coding: utf-8 -*-
"""Pandas_Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEcmfFevJlHlvgxhccSkFKLE7vaoEAuf

#Task 1
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/covid_19_data.csv")
print(df.head(10))
print("\nBefore Conversion:")
print(df.dtypes)
df ["ObservationDate"] = pd.to_datetime(df["ObservationDate"])
df["Last Update"] = pd.to_datetime(df["Last Update"])
print("\nAfter Conversion:")
print(df.dtypes)

"""#Task 2"""

updated_data = df[ (df["Last Update"]=="2020-06-13 03:33:14") ]
print(updated_data.count())
print()
print(updated_data["Country/Region"].unique())

"""#Task 3"""

top_10 = updated_data.sort_values( by="Confirmed", ascending=False).iloc[ 0:10, [3,5,6,7]]
print(top_10)
print("\n",top_10["Country/Region"].unique())

print()
top_10_grps= top_10.groupby("Country/Region").Confirmed.sum().sort_values(ascending=True)
print(top_10_grps)
print("\nCountries with lowest number of confirmed cases: UK")

"""#Task 4"""

top_10["Recovered_percentage"] = top_10["Recovered"]/top_10["Confirmed"]*100
top_10["Deaths_percentage"] = top_10["Deaths"]/top_10["Confirmed"]*100
print(top_10)

sorted_byRate = top_10.sort_values( by="Recovered_percentage",ascending=False)
print(sorted_byRate["Country/Region"].head(3))